version: '3.8'
services:
  eureka-server:
    image: eureka-server
    build: EurekaServerDiscovery/
    ports:
      - "8761:8761"
  config-server:
    image: config-server
    build: ConfigServer/
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"$${eureka_url:http://eureka:abcd1234@eureka-server:8761/eureka}"}}},"spring":{"cloud":{"config":{"server":{"git":{"uri":"file:/opt/app/configRepo"}}}}}}'
    ports:
      - "8888:8888"
  api-gateway:
    build: APIGateway/
    image: api-gateway
    depends_on:
      - eureka-server
      - config-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"$${eureka_url:http://eureka:abcd1234@eureka-server:8761/eureka}"}}}}'
    ports:
      - "9090:9090"
  order-app:
    build: OrderApp/
    image: order-app
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8083:8083"
  product-app:
    build: ProductApp/
    image: product-app
    depends_on:
      - eureka-server
      - config-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"$${eureka_url:http://eureka:abcd1234@eureka-server:8761/eureka}"}}}}'
    ports:
      - "8084-8085:8084"
