eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE
        reactor:
            netty:
                http:
                    client: DEBUG
server:
    port: 9090
spring:
    application:
        name: ApiGateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            httpclient:
                connect-timeout: 1000
                response-timeout: 5s
            routes:
                - id: product_route
                  uri: http://localhost:8084
                  predicates:
                      - Path=/api/product/**
                  filters:
                      #- PrefixPath=/api
                      - RewritePath=/api(?<segment>/?.*), $\{segment}
                      #- RedirectTo=302, https://acme.org
                      - name: Retry
                        args:
                            retries: 3
                            statuses: INTERNAL_SERVER_ERROR,GATEWAY_TIMEOUT
                            methods: GET,POST
                            backoff:
                                firstBackoff: 500ms
                                maxBackoff: 1s
                                factor: 2
                                basedOnPreviousValue: false
                      - name: CircuitBreaker
                        args:
                            name: product_route
                            fallbackuri: forward:/api/error
                - id: order_route
                  uri: http://localhost:8083
                  predicates:
                      - Path=/api/order/**
                  filters:
                      #- PrefixPath=/api
                      - RewritePath=/api(?<segment>/?.*), $\{segment}
                      #- RedirectTo=302, https://acme.org
                      - name: CircuitBreaker
                        args:
                            name: order_route
                            fallbackuri: forward:/api/error
management:
    endpoints:
        web:
            exposure:
                include: "*"